title: Debsoc Blog
email: mvitdebsoc@gmail.com
description: A Blog website for Sir MVIT DEBSOC
author: MvitDebsoc
baseurl: "/DebsocBlog"
url: "https://mvitdebsoc.github.io"

# Social Profiles
twitter_username:
github_username: MvitDebsoc
facebook_username: Sir-MVIT-Parliamentary-Debate-103824854360151/
instagram_username: smvitdebsoc
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Authors
authors:
  author1:
    name: author1
    description: tempore distinctio beatae, aliquid incidunt! tus erex minima possimus?
    avatar: assets/images/avatar/boy1.jpg
    facebook: facebook
    instagram: instagram
    twitter: twitter
  author2:
    name: author 2
    description: Lorem ipsum doloeatae,  repellat assumenda impedit ex minima possimus?
    avatar: assets/images/avatar/girl1.jpg
    facebook: facebook
    instagram: instagram
    twitter: twitter
  author3:
    name: author3
    description: tempore distinctio beatae, aliquid incidunt! tus erex minima possimus?
    avatar: assets/images/avatar/girl2.jpg
    facebook: facebook
    instagram: instagram
    twitter: twitter
  author4:
    name: author 4
    description: Lorem ipsum doloeatae,  repellat assumenda impedit ex minima possimus?
    avatar: assets/images/avatar/boy2.jpg
    facebook: facebook
    instagram: instagram
    twitter: twitter
  author5:
    name: author5
    description: tempore distinctio beatae, aliquid incidunt! tus erex minima possimus?
    avatar: assets/images/avatar/boy3.jpg
    facebook: facebook
    instagram: instagram
    twitter: twitter
  author6:
    name: author 6
    description: Lorem ipsum doloeatae,  repellat assumenda impedit ex minima possimus?
    avatar: assets/images/avatar/girl3.jpg
    facebook: facebook
    instagram: instagram
    twitter: twitter
  author7:
    name: author7
    description: tempore distinctio beatae, aliquid incidunt! tus erex minima possimus?
    avatar: assets/images/avatar/boy4.jpg
    facebook: facebook
    instagram: instagram
    twitter: twitter
  author8:
    name: author 8
    description: Lorem ipsum doloeatae,  repellat assumenda impedit ex minima possimus?
    avatar: assets/images/avatar/girl4.jpg
    facebook: facebook
    instagram: instagram
    twitter: twitter
